"""add manager_key to users

Revision ID: 0016f5eced29
Revises: bc302f67a6e8
Create Date: 2026-05-01 22:45:00.468197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016f5eced29'
down_revision: Union[str, Sequence[str], None] = 'bc302f67a6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'manager_key')
    # ### end Alembic commands ###
