"""add_severity_to_weather_snapshots

Revision ID: 750fc2824e51
Revises: d53f93bb3bd9
Create Date: 2026-04-19 22:05:49.521955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750fc2824e51'
down_revision: Union[str, Sequence[str], None] = 'd53f93bb3bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_snapshots', sa.Column('severity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_snapshots', 'severity')
    # ### end Alembic commands ###
