export interface MockFlight {
    flight: string;
    route: string;
    delay: number;
    status: "DELAYED" | "AT RISK" | "ON TIME";
    hour: string; // e.g., "08:00"
}

export const MOCK_FLIGHTS_BY_AIRPORT: Record<string, MockFlight[]> = {
    ATL: [
        { flight: "DL204", route: "ATL → JFK", delay: 42, status: "DELAYED", hour: "08:00" },
        { flight: "DL887", route: "ATL → LAX", delay: 31, status: "DELAYED", hour: "09:00" },
        { flight: "DL112", route: "ATL → ORD", delay: 18, status: "AT RISK", hour: "10:00" },
        { flight: "DL445", route: "ATL → MIA", delay: 8, status: "ON TIME", hour: "11:00" },
        { flight: "DL667", route: "ATL → DFW", delay: 27, status: "DELAYED", hour: "12:00" },
        { flight: "DL334", route: "ATL → DEN", delay: 14, status: "AT RISK", hour: "13:00" },
        { flight: "DL901", route: "ATL → SFO", delay: 35, status: "DELAYED", hour: "14:00" },
        { flight: "DL223", route: "ATL → SEA", delay: 11, status: "AT RISK", hour: "15:00" },
        { flight: "AA302", route: "ATL → JFK", delay: 0, status: "ON TIME", hour: "16:00" },
        { flight: "WN441", route: "ATL → MIA", delay: 22, status: "DELAYED", hour: "17:00" },
        { flight: "UA556", route: "ATL → ORD", delay: 6, status: "ON TIME", hour: "18:00" },
        { flight: "DL778", route: "ATL → LAX", delay: 39, status: "DELAYED", hour: "19:00" },
        { flight: "B6129", route: "ATL → JFK", delay: 17, status: "AT RISK", hour: "20:00" },
    ],
    JFK: [
        { flight: "AA100", route: "JFK → LAX", delay: 28, status: "DELAYED", hour: "08:00" },
        { flight: "DL402", route: "JFK → ATL", delay: 15, status: "AT RISK", hour: "09:00" },
        { flight: "B6507", route: "JFK → MIA", delay: 33, status: "DELAYED", hour: "10:00" },
        { flight: "UA907", route: "JFK → SFO", delay: 41, status: "DELAYED", hour: "11:00" },
        { flight: "AA180", route: "JFK → LHR", delay: 22, status: "DELAYED", hour: "12:00" },
        { flight: "DL401", route: "JFK → CDG", delay: 18, status: "AT RISK", hour: "13:00" },
        { flight: "B6621", route: "JFK → ORD", delay: 9, status: "ON TIME", hour: "14:00" },
        { flight: "AA302", route: "JFK → DFW", delay: 31, status: "DELAYED", hour: "15:00" },
        { flight: "UA233", route: "JFK → DEN", delay: 7, status: "ON TIME", hour: "16:00" },
        { flight: "DL266", route: "JFK → SEA", delay: 25, status: "DELAYED", hour: "17:00" },
        { flight: "AA116", route: "JFK → MIA", delay: 12, status: "AT RISK", hour: "18:00" },
        { flight: "B6415", route: "JFK → ATL", delay: 0, status: "ON TIME", hour: "19:00" },
        { flight: "UA889", route: "JFK → LAX", delay: 44, status: "DELAYED", hour: "20:00" },
    ],
    ORD: [
        { flight: "UA227", route: "ORD → JFK", delay: 38, status: "DELAYED", hour: "08:00" },
        { flight: "AA312", route: "ORD → LAX", delay: 24, status: "DELAYED", hour: "09:00" },
        { flight: "UA409", route: "ORD → SFO", delay: 19, status: "AT RISK", hour: "10:00" },
        { flight: "AA701", route: "ORD → MIA", delay: 31, status: "DELAYED", hour: "11:00" },
        { flight: "UA141", route: "ORD → DEN", delay: 11, status: "AT RISK", hour: "12:00" },
        { flight: "DL882", route: "ORD → ATL", delay: 8, status: "ON TIME", hour: "13:00" },
        { flight: "UA627", route: "ORD → SEA", delay: 27, status: "DELAYED", hour: "14:00" },
        { flight: "AA2341", route: "ORD → DFW", delay: 15, status: "AT RISK", hour: "15:00" },
        { flight: "UA503", route: "ORD → JFK", delay: 42, status: "DELAYED", hour: "16:00" },
        { flight: "WN601", route: "ORD → MIA", delay: 6, status: "ON TIME", hour: "17:00" },
        { flight: "UA339", route: "ORD → LAX", delay: 33, status: "DELAYED", hour: "18:00" },
        { flight: "AA189", route: "ORD → ATL", delay: 21, status: "DELAYED", hour: "19:00" },
        { flight: "DL445", route: "ORD → JFK", delay: 0, status: "ON TIME", hour: "20:00" },
    ],
    LAX: [
        { flight: "UA2", route: "LAX → JFK", delay: 29, status: "DELAYED", hour: "08:00" },
        { flight: "DL409", route: "LAX → ATL", delay: 17, status: "AT RISK", hour: "09:00" },
        { flight: "AS301", route: "LAX → SEA", delay: 11, status: "AT RISK", hour: "10:00" },
        { flight: "UA889", route: "LAX → ORD", delay: 34, status: "DELAYED", hour: "11:00" },
        { flight: "AA321", route: "LAX → DFW", delay: 22, status: "DELAYED", hour: "12:00" },
        { flight: "DL28", route: "LAX → NRT", delay: 41, status: "DELAYED", hour: "13:00" },
        { flight: "UA838", route: "LAX → SFO", delay: 8, status: "ON TIME", hour: "14:00" },
        { flight: "AS487", route: "LAX → DEN", delay: 25, status: "DELAYED", hour: "15:00" },
        { flight: "AA2490", route: "LAX → MIA", delay: 14, status: "AT RISK", hour: "16:00" },
        { flight: "DL102", route: "LAX → JFK", delay: 38, status: "DELAYED", hour: "17:00" },
        { flight: "UA550", route: "LAX → ORD", delay: 6, status: "ON TIME", hour: "18:00" },
        { flight: "AS201", route: "LAX → SEA", delay: 31, status: "DELAYED", hour: "19:00" },
        { flight: "AA76", route: "LAX → LHR", delay: 19, status: "AT RISK", hour: "20:00" },
    ],
    DFW: [
        { flight: "AA1", route: "DFW → LAX", delay: 26, status: "DELAYED", hour: "08:00" },
        { flight: "AA302", route: "DFW → JFK", delay: 33, status: "DELAYED", hour: "09:00" },
        { flight: "AA607", route: "DFW → MIA", delay: 18, status: "AT RISK", hour: "10:00" },
        { flight: "AA2341", route: "DFW → ORD", delay: 41, status: "DELAYED", hour: "11:00" },
        { flight: "AA431", route: "DFW → ATL", delay: 12, status: "AT RISK", hour: "12:00" },
        { flight: "AA788", route: "DFW → SFO", delay: 29, status: "DELAYED", hour: "13:00" },
        { flight: "AA1925", route: "DFW → DEN", delay: 8, status: "ON TIME", hour: "14:00" },
        { flight: "AA575", route: "DFW → SEA", delay: 22, status: "DELAYED", hour: "15:00" },
        { flight: "UA604", route: "DFW → ORD", delay: 15, status: "AT RISK", hour: "16:00" },
        { flight: "WN234", route: "DFW → MIA", delay: 0, status: "ON TIME", hour: "17:00" },
        { flight: "AA317", route: "DFW → JFK", delay: 37, status: "DELAYED", hour: "18:00" },
        { flight: "AA490", route: "DFW → LAX", delay: 11, status: "AT RISK", hour: "19:00" },
        { flight: "DL882", route: "DFW → ATL", delay: 24, status: "DELAYED", hour: "20:00" },
    ],
    MIA: [
        { flight: "AA901", route: "MIA → JFK", delay: 31, status: "DELAYED", hour: "08:00" },
        { flight: "AA502", route: "MIA → LAX", delay: 24, status: "DELAYED", hour: "09:00" },
        { flight: "DL447", route: "MIA → ATL", delay: 17, status: "AT RISK", hour: "10:00" },
        { flight: "AA911", route: "MIA → GRU", delay: 38, status: "DELAYED", hour: "11:00" },
        { flight: "AA201", route: "MIA → ORD", delay: 22, status: "DELAYED", hour: "12:00" },
        { flight: "UA557", route: "MIA → DEN", delay: 9, status: "ON TIME", hour: "13:00" },
        { flight: "AA487", route: "MIA → DFW", delay: 29, status: "DELAYED", hour: "14:00" },
        { flight: "B6334", route: "MIA → JFK", delay: 14, status: "AT RISK", hour: "15:00" },
        { flight: "AA677", route: "MIA → BOG", delay: 41, status: "DELAYED", hour: "16:00" },
        { flight: "DL221", route: "MIA → ATL", delay: 6, status: "ON TIME", hour: "17:00" },
        { flight: "AA334", route: "MIA → LAX", delay: 33, status: "DELAYED", hour: "18:00" },
        { flight: "WN887", route: "MIA → ATL", delay: 19, status: "AT RISK", hour: "19:00" },
        { flight: "AA156", route: "MIA → MEX", delay: 27, status: "DELAYED", hour: "20:00" },
    ],
    SFO: [
        { flight: "UA11", route: "SFO → JFK", delay: 35, status: "DELAYED", hour: "08:00" },
        { flight: "AS321", route: "SFO → SEA", delay: 12, status: "AT RISK", hour: "09:00" },
        { flight: "UA587", route: "SFO → ORD", delay: 28, status: "DELAYED", hour: "10:00" },
        { flight: "DL609", route: "SFO → ATL", delay: 21, status: "DELAYED", hour: "11:00" },
        { flight: "UA837", route: "SFO → LAX", delay: 8, status: "ON TIME", hour: "12:00" },
        { flight: "AA2490", route: "SFO → DFW", delay: 31, status: "DELAYED", hour: "13:00" },
        { flight: "UA447", route: "SFO → DEN", delay: 17, status: "AT RISK", hour: "14:00" },
        { flight: "AS667", route: "SFO → SEA", delay: 0, status: "ON TIME", hour: "15:00" },
        { flight: "UA839", route: "SFO → NRT", delay: 44, status: "DELAYED", hour: "16:00" },
        { flight: "DL28", route: "SFO → LAX", delay: 14, status: "AT RISK", hour: "17:00" },
        { flight: "UA201", route: "SFO → JFK", delay: 38, status: "DELAYED", hour: "18:00" },
        { flight: "AS109", route: "SFO → PDX", delay: 9, status: "ON TIME", hour: "19:00" },
        { flight: "AA1776", route: "SFO → ORD", delay: 26, status: "DELAYED", hour: "20:00" },
    ],
    DEN: [
        { flight: "UA1523", route: "DEN → LAX", delay: 23, status: "DELAYED", hour: "08:00" },
        { flight: "UA678", route: "DEN → ORD", delay: 31, status: "DELAYED", hour: "09:00" },
        { flight: "F9201", route: "DEN → MIA", delay: 17, status: "AT RISK", hour: "10:00" },
        { flight: "UA404", route: "DEN → JFK", delay: 38, status: "DELAYED", hour: "11:00" },
        { flight: "F9334", route: "DEN → ATL", delay: 12, status: "AT RISK", hour: "12:00" },
        { flight: "UA889", route: "DEN → SFO", delay: 27, status: "DELAYED", hour: "13:00" },
        { flight: "AA1925", route: "DEN → DFW", delay: 8, status: "ON TIME", hour: "14:00" },
        { flight: "UA237", route: "DEN → SEA", delay: 21, status: "DELAYED", hour: "15:00" },
        { flight: "F9445", route: "DEN → LAX", delay: 34, status: "DELAYED", hour: "16:00" },
        { flight: "UA501", route: "DEN → ORD", delay: 6, status: "ON TIME", hour: "17:00" },
        { flight: "DL882", route: "DEN → ATL", delay: 29, status: "DELAYED", hour: "18:00" },
        { flight: "F9112", route: "DEN → MIA", delay: 15, status: "AT RISK", hour: "19:00" },
        { flight: "UA667", route: "DEN → JFK", delay: 41, status: "DELAYED", hour: "20:00" },
    ],
    SEA: [
        { flight: "AS11", route: "SEA → LAX", delay: 19, status: "AT RISK", hour: "08:00" },
        { flight: "AS201", route: "SEA → SFO", delay: 27, status: "DELAYED", hour: "09:00" },
        { flight: "UA627", route: "SEA → ORD", delay: 33, status: "DELAYED", hour: "10:00" },
        { flight: "AS334", route: "SEA → DEN", delay: 14, status: "AT RISK", hour: "11:00" },
        { flight: "DL609", route: "SEA → ATL", delay: 38, status: "DELAYED", hour: "12:00" },
        { flight: "AS487", route: "SEA → LAX", delay: 9, status: "ON TIME", hour: "13:00" },
        { flight: "UA237", route: "SEA → JFK", delay: 41, status: "DELAYED", hour: "14:00" },
        { flight: "AS667", route: "SEA → SFO", delay: 22, status: "DELAYED", hour: "15:00" },
        { flight: "AA575", route: "SEA → DFW", delay: 17, status: "AT RISK", hour: "16:00" },
        { flight: "AS109", route: "SEA → PDX", delay: 6, status: "ON TIME", hour: "17:00" },
        { flight: "DL402", route: "SEA → JFK", delay: 31, status: "DELAYED", hour: "18:00" },
        { flight: "AS321", route: "SEA → LAX", delay: 24, status: "DELAYED", hour: "19:00" },
        { flight: "UA503", route: "SEA → ORD", delay: 28, status: "DELAYED", hour: "20:00" },
    ]
};
